In [137]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://admin:AdminKode_2025!@localhost:3306/brondby")

print("Forbindelse oprettet ✅")

Forbindelse oprettet ✅

In [138]:
df_matches = pd.read_sql("SELECT * FROM matches;", engine)
df_tickets = pd.read_sql("SELECT * FROM tickets;", engine)
df_fb      = pd.read_sql("SELECT * FROM fb_order_lines;", engine)
df_profiles= pd.read_sql("SELECT * FROM profiles;", engine)

print("Matches:", df_matches.shape)
print("Tickets:", df_tickets.shape)
print("FB Orders:", df_fb.shape)
print("Profiles:", df_profiles.shape)

Matches: (156, 10)
Tickets: (1656875, 18)
FB Orders: (2186416, 12)
Profiles: (196649, 7)

Blok A

In [139]:
# billetsalg pr. kamp-id
tickets_per_match = (
    df_tickets.groupby("match_id")["ticket_id"]
              .count()
              .reset_index(name="tickets_sold")
)
tickets_per_match.sort_values("tickets_sold", ascending=False).head(10)

    match_id  tickets_sold
99      5537         24185
53      3161         19432
51      3029         18910
94      5240         18361
21      1742         18235
79      4514         18016
76      4316         17961
74      4151         17886
10       917         17694
83      4712         17586

Blok B

In [140]:

# sørg for tidstyper
df_tickets["attendance"] = pd.to_datetime(df_tickets["attendance"], errors="coerce")
df_matches["Kampdato_dt"] = pd.to_datetime(df_matches["Kampdato"], errors="coerce").dt.date

# brug kun billetter der er scannet
att = df_tickets.dropna(subset=["attendance"]).copy()
att["att_date"] = att["attendance"].dt.date

# mest hyppige attendance-dato pr. match_id (mode)
mode_att_date = (
    att.groupby("match_id")["att_date"]
       .agg(lambda s: s.value_counts().idxmax())
       .reset_index(name="att_date")
)
mode_att_date.head()

   match_id    att_date
0       621  2022-07-17
1       622  2022-07-24
2       623  2022-08-14
3       624  2022-08-29
4       653  2022-07-28

Blok C

In [141]:
mapping = mode_att_date.merge(
    df_matches,
    left_on="att_date",
    right_on="Kampdato_dt",
    how="left"
)[["match_id","Kampnavn","Kampdato","Kampstart","Sæson","Turnering","Turneringstype"]]

mapping.head(10)

,match_id,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Turneringstype
0,621,2022-07-17 | Brøndby IF - AGF,2022-07-17,2022-07-17 18:00:00,2022/23,Superliga,Superliga
1,622,2022-07-24 | Brøndby IF - FC Nordsjælland,2022-07-24,2022-07-24 16:00:00,2022/23,Superliga,Superliga
2,623,2022-08-14 | Brøndby IF - OB,2022-08-14,2022-08-14 18:00:00,2022/23,Superliga,Superliga
3,624,2022-08-29 | Brøndby IF - FC Midtjylland,2022-08-29,2022-08-29 19:00:00,2022/23,Superliga,Superliga
4,653,2022-07-28 | Brøndby IF - Pogoń Szczecin,2022-07-28,2022-07-28 20:00:00,2022/23,UEFA Europa Conference League,UEFA
5,719,2022-08-04 | Brøndby IF - FC Basel,2022-08-04,2022-08-04 20:30:00,2022/23,UEFA Europa Conference League,UEFA
6,752,2022-09-11 | Brøndby IF - Randers FC,2022-09-11,2022-09-11 16:00:00,2022/23,Superliga,Superliga
7,818,2022-10-02 | Brøndby IF - Lyngby BK,2022-10-02,2022-10-02 16:00:00,2022/23,Superliga,Superliga
8,851,2022-10-30 | Brøndby IF - AaB,2022-10-30,2022-10-30 18:00:00,2022/23,Superliga,Superliga
9,884,2022-11-13 | Brøndby IF - Viborg FF,2022-11-13,2022-11-13 16:00:00,2022/23,Superliga,Superliga

Blok D.1

In [142]:
tickets_per_match = (
    df_tickets.groupby("match_id")["ticket_id"]
              .count()
              .reset_index(name="tickets_sold")
)

Blok D.2

In [143]:
tickets_with_names = tickets_per_match.merge(mapping, on="match_id", how="left")
tickets_with_names = tickets_with_names.sort_values("tickets_sold", ascending=False)
tickets_with_names.head(10)   # Top 10 kampe

,match_id,tickets_sold,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Turneringstype
99,5537,24185,2025-08-28 | Brøndby IF - RC Strasbourg,2025-08-28,2025-08-28 20:00:00,2025/26,UEFA Europa Conference League,UEFA
53,3161,19432,2024-08-08 | Brøndby IF - Legia Warszawa,2024-08-08,2024-08-08 19:00:00,2024/25,UEFA Europa Conference League,UEFA
51,3029,18910,2024-07-25 | Brøndby IF - KF Llapi,2024-07-25,2024-07-25 19:00:00,2024/25,UEFA Europa Conference League,UEFA
94,5240,18361,2025-08-14 | Brøndby IF - Vikingur Reykjavik,2025-08-14,2025-08-14 19:30:00,2025/26,UEFA Europa Conference League,UEFA
21,1742,18235,2023-09-24 | Brøndby IF - FC København,2023-09-24,2023-09-24 14:00:00,2023/24,Superliga,Superliga
79,4514,18016,2025-04-18 | Brøndby IF - FC Nordsjælland,2025-04-18,2025-04-18 19:00:00,2024/25,Superliga,Superliga
76,4316,17961,2025-03-16 | Brøndby IF - Silkeborg IF,2025-03-16,2025-03-16 17:00:00,2024/25,Superliga,Superliga
74,4151,17886,2025-02-14 | Brøndby IF - Viborg FF,2025-02-14,2025-02-14 19:00:00,2024/25,Superliga,Superliga
10,917,17694,2022-10-16 | Brøndby IF - FC København,2022-10-16,2022-10-16 14:00:00,2022/23,Superliga,Superliga
83,4712,17586,2025-05-04 | Brøndby IF - FC København,2025-05-04,2025-05-04 16:00:00,2024/25,Superliga,Superliga

Views

In [144]:
ticket_types = (
    df_tickets.groupby(["match_id","ticket_type"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="ticket_type", values="count")
              .fillna(0)
              .reset_index()
)

In [145]:
sections = (
    df_tickets.groupby(["match_id","section_display"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="section_display", values="count")
              .fillna(0)
              .reset_index()
)

In [146]:
tickets_full = (tickets_with_names
    .merge(avg_scans, on="match_id", how="left")
    .merge(peak_scans[["match_id","peak_minute","peak_scans"]], on="match_id", how="left")
    .merge(ticket_types, on="match_id", how="left")      # <-- nyt
    .merge(sections, on="match_id", how="left")          # <-- nyt
)

tickets_full.head(10)

,match_id,tickets_sold,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Turneringstype,avg_scans_per_minute,peak_minute,...,Vilfort Lounge_Blok 5,Vilfort Lounge_Blok 6,Vilfort Lounge_Hertha BSC Lounge,Vilfort Lounge_Legende Logen,Vilfort Lounge_Tårn 2,Vilfort Lounge_Tårn 3,Vilfort Lounge_Tårn 4,Vilfort Lounge_Tårn 5,Vilfort Lounge_Tårn 6,Zachodnia_225
0,5537,24185,2025-08-28 | Brøndby IF - RC Strasbourg,2025-08-28,2025-08-28 20:00:00,2025/26,UEFA Europa Conference League,UEFA,100.487395,2025-08-28 19:20:00,...,13.0,22.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3161,19432,2024-08-08 | Brøndby IF - Legia Warszawa,2024-08-08,2024-08-08 19:00:00,2024/25,UEFA Europa Conference League,UEFA,81.556485,2024-08-08 18:31:00,...,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3029,18910,2024-07-25 | Brøndby IF - KF Llapi,2024-07-25,2024-07-25 19:00:00,2024/25,UEFA Europa Conference League,UEFA,79.367257,2024-07-25 18:17:00,...,21.0,2.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5240,18361,2025-08-14 | Brøndby IF - Vikingur Reykjavik,2025-08-14,2025-08-14 19:30:00,2025/26,UEFA Europa Conference League,UEFA,73.406780,2025-08-14 18:57:00,...,14.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1742,18235,2023-09-24 | Brøndby IF - FC København,2023-09-24,2023-09-24 14:00:00,2023/24,Superliga,Superliga,109.948936,2023-09-24 13:09:00,...,0.0,0.0,18.0,0.0,49.0,34.0,21.0,16.0,23.0,0.0
5,4514,18016,2025-04-18 | Brøndby IF - FC Nordsjælland,2025-04-18,2025-04-18 19:00:00,2024/25,Superliga,Superliga,106.515556,2025-04-18 18:29:00,...,33.0,7.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0
6,4316,17961,2025-03-16 | Brøndby IF - Silkeborg IF,2025-03-16,2025-03-16 17:00:00,2024/25,Superliga,Superliga,101.855932,2025-03-16 16:39:00,...,23.0,17.0,0.0,44.0,0.0,0.0,0.0,0.0,0.0,0.0
7,4151,17886,2025-02-14 | Brøndby IF - Viborg FF,2025-02-14,2025-02-14 19:00:00,2024/25,Superliga,Superliga,104.947598,2025-02-14 18:29:00,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0
8,917,17694,2022-10-16 | Brøndby IF - FC København,2022-10-16,2022-10-16 14:00:00,2022/23,Superliga,Superliga,104.080717,2022-10-16 13:10:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,4712,17586,2025-05-04 | Brøndby IF - FC København,2025-05-04,2025-05-04 16:00:00,2024/25,Superliga,Superliga,112.915966,2025-05-04 15:35:00,...,31.0,21.0,0.0,46.0,0.0,0.0,0.0,0.0,0.0,0.0